In [2]:
import numpy as np

In [3]:
#How do you create a NumPy array from the list [1, 2, 3, 4, 5]

l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [4]:
#What is the output of np.array([10, 20, 30, 40])[2]
l1 = [10, 20, 30, 40]
arr = np.array(l1)
arr

print(np.array([10, 20, 30, 40])[2])

30


In [5]:
#Create a NumPy array containing integers from 1 to 10
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#Create a NumPy array containing five zeros.
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [7]:
#Create a 3 × 3 NumPy array containing only ones.
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#What is the shape of np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1
arr1.shape

(2, 3)

In [9]:
#What is the number of dimensions of np.array([[1, 2], [3, 4], [5, 6]])?
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
arr2.shape

(3, 2)

In [10]:
#Given arr = np.array([10, 20, 30, 40, 50]), extract the elements from index 1 to index 3.

arr = np.array([10, 20, 30, 40, 50])
arr[1:3]

array([20, 30])

In [11]:
# Given arr = np.array([1, 2, 3, 4, 5]), multiply every element by 10.
arr = np.array([1, 2, 3, 4, 5])
arr = arr*10
arr

array([10, 20, 30, 40, 50])

In [12]:
#Find the sum, mean, maximum, and minimum of np.array([12, 5, 8, 20, 15]).
arr = np.array([12, 5, 8, 20, 15])
print("Sum : ", arr.sum())
print("Mean : ", arr.mean())
print("Maximun : ",arr.max())
print("Minimum : ",arr.min())

Sum :  60
Mean :  12.0
Maximun :  20
Minimum :  5


In [13]:
#Given arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), extract only the even numbers.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
result = arr[arr % 2 == 0]
print(result)

[ 2  4  6  8 10]


In [14]:
#Sort np.array([5, 2, 8, 1, 9, 3]) in ascending order.
arr = np.array([5, 2, 8, 1, 9, 3]) 
(arr.sort())
arr

array([1, 2, 3, 5, 8, 9])

In [15]:
#Find the indices of elements greater than 50 in np.array([10, 60, 30, 80, 45, 90]).
arr = np.array([10, 60, 30, 80, 45, 90])
print(arr[arr>50])

[60 80 90]


In [16]:
#Reshape np.array([1, 2, 3, 4, 5, 6]) into a 2 × 3 array.
arr = np.array([1, 2, 3, 4, 5, 6])
result = arr.reshape(2,3)
result

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#Given two arrays [1, 2, 3] and [4, 5, 6], perform element-wise addition, subtraction, multiplication, and division.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition : ", arr1 + arr2)
print("Substraction : ", arr1 - arr2)
print("Multiplication : ", arr1*arr2)
print("Division : ", arr1/arr2)

Addition :  [5 7 9]
Substraction :  [-3 -3 -3]
Multiplication :  [ 4 10 18]
Division :  [0.25 0.4  0.5 ]


In [18]:
#Perform matrix multiplication on [[1, 2], [3, 4]] and [[5, 6], [7, 8]].
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = arr1@arr2
print("Matrix 1: \n",arr1)
print("Matrix 2: \n",arr2)
print("Matrix multiplication: \n", result)

Matrix 1: 
 [[1 2]
 [3 4]]
Matrix 2: 
 [[5 6]
 [7 8]]
Matrix multiplication: 
 [[19 22]
 [43 50]]


In [19]:
#Find the transpose of [[1, 2, 3], [4, 5, 6]].
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Before transpose: \n", arr)

print("After transpose: \n",arr.T)

Before transpose: 
 [[1 2 3]
 [4 5 6]]
After transpose: 
 [[1 4]
 [2 5]
 [3 6]]


In [20]:
#Replace all values greater than 3 with 100 in np.array([1, 2, 3, 4, 5]).
arr = np.array([1, 2, 3, 4, 5])
print("GIVEN ARRAY: \n" ,arr)
arr[arr>3]=100
print("AFTER REPLACING: \n",arr)

GIVEN ARRAY: 
 [1 2 3 4 5]
AFTER REPLACING: 
 [  1   2   3 100 100]


In [21]:
#Create a 5 × 5 array containing numbers from 1 to 25 and extract the second row and third column.
arr1 = np.arange(1,26)
arr = arr1.reshape(5,5)
print("Matrix: \n",arr)
print("Second row: \n", arr[1 ,:])
print("Third column: \n", arr[:,2])

Matrix: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Second row: 
 [ 6  7  8  9 10]
Third column: 
 [ 3  8 13 18 23]


In [22]:
#Given [[10, 20, 30], [40, 50, 60], [70, 80, 90]], find the row sums, column sums, overall mean, and elements greater than 45.
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Row sums
print("Row sums:", arr.sum(axis=1))

# Column sums
print("Column sums:", arr.sum(axis=0))

# Overall mean
print("Overall mean:", arr.mean())

# Elements greater than 45
print("Elements greater than 45:", arr[arr > 45])

Row sums: [ 60 150 240]
Column sums: [120 150 180]
Overall mean: 50.0
Elements greater than 45: [50 60 70 80 90]


In [23]:
#Create a NumPy array containing all even numbers from 2 to 20.
arr = np.arange(2, 21, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [24]:
#Create a NumPy array containing 10 equally spaced values between 0 and 1.
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
#Given arr = np.array([3, 7, 2, 9, 4, 8]), find the Index of the maximum value.
arr = np.array([3, 7, 2, 9, 4, 8])
print("Index of the maximum value: ", arr.argmax())

Index of the maximum value:  3


In [26]:
#Given arr = np.array([10, 20, 30, 40, 50]), reverse the array.
arr = np.array([10, 20, 30, 40, 50])
print("Current array: ",arr)
result = arr[::-1]
print("Reversed array: ",result)

Current array:  [10 20 30 40 50]
Reversed array:  [50 40 30 20 10]


In [27]:
#Find the unique values in np.array([1, 2, 2, 3, 4, 4, 5]).
arr = np.array([1, 2, 2, 3, 4, 4, 5])
print('Array with dublicate values: \n', arr)
result = np.unique(arr)
print("Array with unique values: \n", result)

Array with dublicate values: 
 [1 2 2 3 4 4 5]
Array with unique values: 
 [1 2 3 4 5]


In [28]:
#Count how many elements are greater than 25 in np.array([10, 30, 15, 40, 25, 50]).
arr = np.array([10, 30, 15, 40, 25, 50])
result = np.sum(arr > 25)
print("Array : \n", arr)
print("Total number greater than 23: ",result)

Array : 
 [10 30 15 40 25 50]
Total number greater than 23:  3


In [29]:
#Convert the following 1D array into a 3 × 3 array: np.array([1,2,3,4,5,6,7,8,9]).
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("3x3 Array: \n", arr.reshape(3,3))

3x3 Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
#Flatten the array [[1, 2], [3, 4], [5, 6]] into a 1D array.
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix : \n ", arr)
print("1D array : \n", arr.flatten())

Matrix : 
  [[1 2]
 [3 4]
 [5 6]]
1D array : 
 [1 2 3 4 5 6]


In [31]:
# Concatenate np.array([1,2,3]) and np.array([4,5,6]).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1,arr2))
print("Concatenate Array: ", result)

Concatenate Array:  [1 2 3 4 5 6]


In [32]:
#Split np.array([1,2,3,4,5,6]) into three equal parts.
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)
print("Three Equal Parts:")
print(result)


Three Equal Parts:
[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
#Find the standard deviation of np.array([10, 20, 30, 40, 50]).
arr = np.array([10, 20, 30, 40, 50])
result = np.std(arr)
print("Standard Deviation:", result)


Standard Deviation: 14.142135623730951


In [34]:
#Find the variance of np.array([2, 4, 6, 8, 10]).
arr = np.array([2, 4, 6, 8, 10])
result = np.var(arr)
print("Variance:", result)


Variance: 8.0


In [35]:
#Given arr = np.array([1, 2, 3, 4, 5]), calculate the cumulative sum.
arr = np.array([1, 2, 3, 4, 5])
result = np.cumsum(arr)
print("Cumulative Sum:", result)


Cumulative Sum: [ 1  3  6 10 15]


In [36]:
#Given arr = np.array([1, 2, 3, 4, 5]), calculate the cumulative product.
arr = np.array([1, 2, 3, 4, 5])

result = np.cumprod(arr)

print("Cumulative Product:", result)


Cumulative Product: [  1   2   6  24 120]


In [37]:
#Replace all odd numbers with -1 in np.array([1,2,3,4,5,6,7]).

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[arr % 2 != 0] = -1

print("Odd numbers replaced with -1:")
print(arr)

Odd numbers replaced with -1:
[-1  2 -1  4 -1  6 -1]


In [38]:
#Find the maximum value in each row of [[1,5,3],[8,2,6],[4,9,7]].
arr = np.array([
    [1, 5, 3],
    [8, 2, 6],
    [4, 9, 7]
])

result = np.max(arr, axis=1)

print("Maximum value of each row:")
print(result)



Maximum value of each row:
[5 8 9]


In [39]:
#Find the minimum value in each column of [[5,2,8],[1,7,3],[6,4,9]].
arr = np.array([[5,2,8],[1,7,3],[6,4,9]])
print(arr)
result = np.min(arr, axis=0)

print("Minimun value of each column:")
print(result)

[[5 2 8]
 [1 7 3]
 [6 4 9]]
Minimun value of each column:
[1 2 3]


In [40]:
#Create a 4 × 4 identity matrix

result = np.eye(4)

print("4 × 4 Identity Matrix:")
print(result)




4 × 4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
#Generate a 3 × 3 matrix of random integers between 1 and 20

result = np.random.randint(1, 21, size=(3, 3))

print("Random 3 × 3 Matrix:")
print(result)


Random 3 × 3 Matrix:
[[16 11 14]
 [ 3 20 13]
 [10  6  8]]


In [42]:
#Given two NumPy arrays, find the elements that are common to both arrays.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

result = np.intersect1d(arr1, arr2)

print("Common elements:")
print(result)

Common elements:
[3 4 5]


In [43]:
#Exercises

# Columns: Age, Math, Science
students = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [20, 76, 95],
    [18, 89, 72],
    [21, 65, 80]
])
print(students)

[[18 85 78]
 [19 92 88]
 [20 76 95]
 [18 89 72]
 [21 65 80]]


In [44]:
#Get the shape of the matrix.
print(students.shape)

(5, 3)


In [45]:
#Find the average age of students.
print("Mean students Age: ",students[:,0].mean())

Mean students Age:  19.2


In [46]:
#Extract the Math marks of all students.
print('Maths Marks: ', students[:,1])

Maths Marks:  [85 92 76 89 65]


In [47]:
#Find the highest Science mark.
print("Highest Marks in Science : ", students[:,2].max())

Highest Marks in Science :  95


In [48]:
#Get the details of the student who scored more than 90 in Math.
print("Details of students who scored more than 90 in Maths")
print(students[students[:,1]>90])

Details of students who scored more than 90 in Maths
[[19 92 88]]


In [49]:
#Increase the Math marks of all students by 5.
students[:,1] = students[:,1]+5
print(students)

[[18 90 78]
 [19 97 88]
 [20 81 95]
 [18 94 72]
 [21 70 80]]


In [50]:
#Find how many students are younger than 19.
print(np.sum(students[:, 0] < 19))


2


In [51]:
#Calculate the average marks in each subject (column-wise mean).
print(np.mean(students[:, 1:], axis=0))

[86.4 82.6]


In [52]:
#Get the data of students who scored at least 80 in both subjects.
result = students[(students[:, 1] >= 80) & (students[:, 2] >= 80)]

print(result)

[[19 97 88]
 [20 81 95]]


In [53]:
#Replace all Science marks below 75 with 0.
students[students[:, 2] < 75, 2] = 0

print(students)

[[18 90 78]
 [19 97 88]
 [20 81 95]
 [18 94  0]
 [21 70 80]]
